---
abstract: 'Email address loose validation type constraint for Moose.'
author:
  - 'hayajo <hayajo@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  namespace::autoclean: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-Types-Email-Loose
no_index:
  directory:
    - inc
    - t
requires:
  Email::Valid::Loose: 0
  Moose: 0
  MooseX::Types::Common: 0
  MooseX::Types::Email: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: https://github.com/hayajo/MooseX-Types-Email-Loose.git
version: 0.01
